name: wach_store_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib\assets\watches_PNG9866.png
  - lib\assets\OIP.jpg
  - lib\assets\Black-watch-PNG.png
  - lib\assets\Fender-Jazzmaster.jpg
  - lib\assets\png-Brawn-watch.png
  - lib\assets\brawn.jpg
  - lib\assets\blue.jpg
  - lib\assets\backgraund.jpg
