name: store_watch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/background_watch.jpeg
  uses-material-design: true
  fonts:
    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif_Condensed-ExtraLight.ttf
        - asset: fonts/NotoSerif_SemiCondensed-SemiBold.ttf