name: shopingpriject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.6.1
  google_nav_bar: ^5.0.6
  dot_navigation_bar:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    
    - lib\assets\imges\img10.png
    - lib\assets\imges\img5.png
    - lib\assets\imges\img4.png